"""initial_schema

Revision ID: 7dea379d9041
Revises: 
Create Date: 2026-08-30 18:48:38.001314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7dea379d9041'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    import models
    bind = op.get_bind()
    models.Base.metadata.create_all(bind=bind)

    insp = sa.inspect(bind)
    if insp.has_table('customers'):
        try:
            op.alter_column('customers', 'ai_disabled',
                       existing_type=sa.BOOLEAN(),
                       server_default=None,
                       existing_nullable=True)
        except Exception:
            pass

    if insp.has_table('order_items'):
        try:
            op.create_foreign_key(None, 'order_items', 'products', ['product_id'], ['id'])
        except Exception:
            pass

    if insp.has_table('orders'):
        try:
            op.alter_column('orders', 'channel',
                       existing_type=sa.VARCHAR(),
                       server_default=None,
                       existing_nullable=True)
            op.alter_column('orders', 'is_restocked',
                       existing_type=sa.BOOLEAN(),
                       server_default=None,
                       existing_nullable=True)
        except Exception:
            pass

    if insp.has_table('products'):
        try:
            op.alter_column('products', 'stock_qty',
                       existing_type=sa.INTEGER(),
                       type_=sa.Float(),
                       existing_nullable=True)
            op.alter_column('products', 'low_stock_threshold',
                       existing_type=sa.INTEGER(),
                       type_=sa.Float(),
                       existing_nullable=True)
            op.alter_column('products', 'unit_multiplier',
                       existing_type=sa.INTEGER(),
                       type_=sa.Float(),
                       existing_nullable=True)
            op.alter_column('products', 'is_customer_facing',
                       existing_type=sa.BOOLEAN(),
                       server_default=None,
                       existing_nullable=True)
        except Exception:
            pass

    if insp.has_table('stock_movements'):
        try:
            op.alter_column('stock_movements', 'quantity_change',
                       existing_type=sa.INTEGER(),
                       type_=sa.Float(),
                       existing_nullable=False)
            op.alter_column('stock_movements', 'quantity_after',
                       existing_type=sa.INTEGER(),
                       type_=sa.Float(),
                       existing_nullable=False)
        except Exception:
            pass

    if insp.has_table('tasks'):
        try:
            op.alter_column('tasks', 'requires_report',
                       existing_type=sa.BOOLEAN(),
                       server_default=None,
                       existing_nullable=True)
        except Exception:
            pass


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'requires_report',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('stock_movements', 'quantity_after',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('stock_movements', 'quantity_change',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('products', 'is_customer_facing',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('products', 'unit_multiplier',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('products', 'low_stock_threshold',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('products', 'stock_qty',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('orders', 'is_restocked',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('orders', 'channel',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'b2c'"),
               existing_nullable=True)
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.alter_column('customers', 'ai_disabled',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('0'),
               existing_nullable=True)
    # ### end Alembic commands ###
